project:
  type: website
  output-dir: docs

website:
  title: "Rayne Aurit's Portfolio"
  favicon: "favicon.png"
  navbar:
    right:
      - Resume/ResumeRayneAurit.qmd
      - about.qmd
      - icon: github
        href: https://github.com/raurit
      - icon: linkedin
        href: https://www.linkedin.com/in/rayne-aurit-08538a29a/

format:
  html:
    theme:
      - united
      - brand
    css: styles.css



